### ISSUE TITLE
Deprecating Per Form Emails in version 1.1

### ISSUE THREAD

**Issue by mathetos** [WordImpress/Give-Per-Form-Emails#12]
Two issues that should be finalized:

1) The language of the admin alert proposed in version 1.1. This is what I suggest instead:
> $message = sprintf( __( '<strong>Give - Per Form Emails:</strong> Your database needs to be updated. Click here to update Per Form Emails to be compatible with <strong>Give 2.0</strong>. After upgrading your database, please deactivate this add-on. All features of this add-on are now covered in <strong>Give 2.0</strong>.', 'give-per-form-emails' ), 'https://wordpress.org/plugins/give' );
Ref: https://github.com/WordImpress/Give-Per-Form-Emails/blob/release/1.1/give-per-form-emails.php#L170

2) Besides the database update and this one notice, I think there should be a non-dismissable notice that appears after the database update is run that says this:
> <strong>Give - Per Form Emails:</strong> We noticed you have run your database update for this add-on, but it is still activated. Please deactivate and delete this add-on. It is no longer developed or supported since all features are now covered in Give Core since version 2.0.

Adding this secondary notice after database updates are run ensures that the appropriate steps are taken by the admin.

**Comment by ravinderk** [comment]
@mathetos can we close this issue?
